#!/usr/bin/env python3

import sys
from question_answerer import qa_main

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: ./answer article.txt questions.txt")
        sys.exit(1)

    article = sys.argv[1]
    questions = sys.argv[2]

    with open(article, 'r', encoding='utf8') as f:
        article_text = f.read()

    with open(questions, 'r', encoding='utf8') as f:
        questions_text = f.readlines()

    question_list = [q.strip() for q in questions_text]

    # answers = generate_answers(article_text, questions_text)
    # print(question_list)
    answers = qa_main.get_answers(article_text, question_list)

    for answer in answers:
        print(answer)
