#!/usr/bin/env python3

import sys
from question_generator import qg_main


def generate_questions(wiki_text_block, no_of_questions):
    """
    generates the questions based on the wiki text and returns the no of
    questions based on the no_of_questions parameter
        :param wiki_text_block: Wikipedia text
        :param no_of_questions: no of questions to be generated by the generator
    """
    questions = qg_main.get_questions(wiki_text_block, int(no_of_questions))

    # map questions list to no_of_questions
    return questions


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: ./ask article.txt nquestions")
        sys.exit(1)

    article = sys.argv[1]
    nquestions = sys.argv[2]

    with open(article, 'r', encoding='utf8') as f:
        article_text = f.read()

    questions = generate_questions(article_text, nquestions)

    for question in questions:
        print(question)
