from question_answering import qa_main
from question_generator import qg_main

def generate_questions(wiki_text_block, no_of_questions):
    """
    generates the questions based on the wiki text and returns the no of 
    questions based on the no_of_questions parameter
        :param wiki_text_block: Wikipedia text
        :param no_of_questions: no of questions to be generated by the generator
    """
    questions = qg_main.get_questions(wiki_text_block)
    
    # map questions list to no_of_questions
    return questions


def generate_answer(wiki_text_block, question):
    """
    returns an answer to the question based on the wiki text
        :param wiki_text_block: Wikipedia text
        :param question: question to be answered
    """
    answer = qa_main.get_answer(wiki_text_block, question)
    return answer